### ISSUE TITLE
PropertyNamingStrategyWrapper looks for deprecated PropertyNamingStrategy.LOWER_CAMEL_CASE

### ISSUE THREAD

**Issue by alievrenkut** [HubSpot/jackson-datatype-protobuf#95] opened 2022-12-15 12:21 UTC
New version of Jackson start using PropertyNamingStrategies.LOWER_CAMEL_CASE for default. Could you update the code to check for this for NoOpNamingStrategy. Below you can find suggested change:

```
public PropertyNamingStrategyWrapper(PropertyNamingStrategy delegate) {
        if (delegate instanceof PropertyNamingStrategy.PropertyNamingStrategyBase) {
            this.delegate = (PropertyNamingStrategy.PropertyNamingStrategyBase)delegate;
        } else if (delegate == PropertyNamingStrategy.LOWER_CAMEL_CASE 
|| delegate == PropertyNamingStrategies.LOWER_CAMEL_CASE) { // suggested change
            this.delegate = NO_OP;
        } else {
            this.delegate = SNAKE_TO_CAMEL;
        }

    }
```

**Comment by jhaber** [comment] 2023-07-13 15:47
👋 which version of jackson has this change? I'm not able to reproduce on jackson 2.12, 2.13, 2.14, or 2.15

**Comment by cowtowncoder** [comment] 2023-07-13 22:22
I am not aware of any change in Jackson to force naming strategy, or change defaults.

But I assume this might be about deprecation of constants in `PropertyNamingStrategy` (as per https://github.com/FasterXML/jackson-databind/issues/2715) and moving to use ones from `PropertyNamingStrategies` instead.
This change would have gone in 2.12.0.

**Comment by jhaber** [comment] 2023-07-14 12:35
I believe that was handled in #88 Going to close this out, but feel free to reopen if I missed something

**Closed by jhaber** 2023-07-14 12:35 UTC

**Comment by slankka** [comment] 2025-02-12 10:09
Notice:

0.9.14 is the last version refering to `PropertyNamingStrategy`, this change requires jackson-2.12 because of `PropertyNamingStrategies`, lower version will throw exceptions:

```
java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.PropertyNamingStrategies$NamingBase
```

https://github.com/FasterXML/jackson-databind/issues/2715
